### ISSUE TITLE
Limit access to this repo

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-content-experiments#10]
I believe there are currently ~19 people (fxaccounts group) which have full commit access to this repo.
We probably want to limit access to a list of 3-4 admins, who approve and merge PRs.

**Comment by rfk** [comment]
I made a new "fxa-admins" team with @vladikoff @jrgm @shane-tomlinson @dannycoates and @rfk and made it admin on this repo, removing the broader "fxaccounts" team.  We can refine things from there, but since as @dannycoates points out that "merges to this repo are 10 minutes from production" I figured we may as well get something in place quickly.
